name: Publish Release

on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Validate Gradle wrapper
      uses: gradle/actions/wrapper-validation@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Build with Gradle
      run: ./gradlew build test --stacktrace --scan

    - name: Set version
      id: set-version
      run: |
        projectVersion=$(grep '^maven_version=' gradle.properties | cut -d'=' -f2)
        echo "version=$projectVersion" >> $GITHUB_OUTPUT

    - name: Upload a jar Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: PistonMOTD
        path: build/libs/PistonMOTD-${{ steps.set-version.outputs.version }}.jar
        if-no-files-found: error

    - name: Build Changelog
      id: github_release
      uses: mikepenz/release-changelog-builder-action@v5
      with:
        mode: COMMIT
        configurationJson: |
          {
            "template": "#{{CHANGELOG}}",
            "categories": [
              {
                  "title": "## Feature",
                  "labels": ["feat", "feature"]
              },
              {
                  "title": "## Fix",
                  "labels": ["fix", "bug"]
              },
              {
                  "title": "## Performance",
                  "labels": ["perf"]
              },
              {
                  "title": "## Refactor",
                  "labels": ["refactor"]
              },
              {
                  "title": "## Documentation",
                  "labels": ["docs"]
              },
              {
                  "title": "## Build",
                  "labels": ["build", "chore", "ci"]
              },
              {
                  "title": "## Style",
                  "labels": ["style"]
              },
              {
                  "title": "## Test",
                  "labels": ["test"]
              },
              {
                  "title": "## Other",
                  "labels": []
              }
            ],
            "label_extractor": [
              {
                "pattern": "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\\([\\w\\-\\.]+\\))?(!)?: ([\\w ])+([\\s\\S]*)",
                "on_property": "title",
                "target": "$1"
              }
            ]
          }
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: Kir-Antipov/mc-publish@v3.3
      with:
        modrinth-id: pistonmotd
        modrinth-featured: true
        modrinth-unfeature-mode: subset
        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

        github-tag: ${{ steps.set-version.outputs.version }}
        github-generate-changelog: false
        github-draft: false
        github-prerelease: false
        github-commitish: main
        github-token: ${{ secrets.GITHUB_TOKEN }}

        files: |
          build/libs/PistonMOTD-${{ steps.set-version.outputs.version }}.jar

        name: PistonMOTD ${{ steps.set-version.outputs.version }}
        version: ${{ steps.set-version.outputs.version }}
        version-type: release
        changelog: ${{ steps.github_release.outputs.changelog }}

        loaders: |
          bukkit
          bungeecord
          folia
          paper
          purpur
          spigot
          sponge
          velocity
          waterfall
        game-versions: |
          >=1.8.0
        game-version-filter: releases
        java: |
          8
          11
          17
          21

        retry-attempts: 2
        retry-delay: 10000
        fail-mode: fail

    - name: Upload to Ore
      uses: dualspiral/ore-upload-action@v1
      with:
        plugin: PistonMOTD
        apiKey: ${{ secrets.ORE_TOKEN }}
        channel: Release
        pluginId: pistonmotd
        createForumPost: true
        description: ''

    - name: Discord Webhook Action
      uses: tsickert/discord-webhook@v7.0.0
      with:
        webhook-url: ${{ secrets.WEBHOOK_URL }}
        content: <@&850705047938793503> New PistonMOTD version released!
        embed-title: PistonMOTD ${{ steps.set-version.outputs.version }}
        embed-description: PistonMOTD ${{ steps.set-version.outputs.version }} has been released! Changelog and download can be found at https://modrinth.com/plugin/pistonmotd/version/${{ steps.set-version.outputs.version }}
        embed-color: 16641028
        embed-thumbnail-url: https://raw.githubusercontent.com/AlexProgrammerDE/PistonMOTD/refs/heads/main/images/logo.png
